# Copyright Advanced Micro Devices, Inc.
# Copyright (c) 2023, 2024 Red Hat, Inc.
#
# SPDX-License-Identifier: MIT

name = "rocFFT"
supported_isas = [1201]
extra_args = []

[ubuntu]
test_package_name = "librocfft0-tests"
test_debug_package_names = ["librocfft0-tests-dbgsym", "librocfft0-dbgsym", "libhsa-runtime64-1-dbgsym", "libamdhip64-7-dbgsym", "libamd-comgr3-dbgsym"]
test_binary_path = "/usr/libexec/rocm/librocfft0-tests/"
test_binaries = ["rocfft-test"]

[fedora]
test_package_name = "rocfft-test"
test_debug_package_names = ["rocfft-tests-debuginfo", "rocfft-debuginfo", "rocm-runtime-debuginfo", "rocm-comgr-debuginfo", "rocm-hip-debuginfo"]
test_binary_path = "/usr/bin/"
test_binaries = ["rocfft-test"]
