# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

name = "hipFFT"
supported_isas = [1201]
extra_args = []

[ubuntu]
test_package_name = "libhipfft0-tests"
test_debug_package_names = ["libhipfft0-tests-dbgsym", "libhipfft0-dbgsym", "librocfft0-dbgsym", "libhsa-runtime64-1-dbgsym", "libamdhip64-7-dbgsym", "libamd-comgr3-dbgsym"]
test_binary_path = "/usr/libexec/rocm/libhipfft0-tests/"
