# Copyright Advanced Micro Devices, Inc.
#
# SPDX-License-Identifier: MIT

name = "rocTHRUST"
supported_isas = [1201]
extra_args = []

[ubuntu]
test_package_name = "librocthrust-tests"
test_debug_package_names = ["librocthrust-tests-dbgsym", "librocthrust-dbgsym", "libhsa-runtime64-1-dbgsym", "libamdhip64-7-dbgsym", "libamd-comgr3-dbgsym"]
test_binary_path = "/usr/libexec/rocm/librocthrust-tests/"
